### PR TITLE
Page expiry issue Fixes #1212

### LINKED ISSUE #1212: Page expires after some time on form submit

### PR DESCRIPTION
**Pull request by ashu555**

### CODE REVIEW

**Comment by bhanu2217** [comment]
From a user experience perspective, this P.R should be given high priority after security releases are tested and merged.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Step to reproduce this session out the issue:-
1. open session .php and  line no 32 lifetime equal to 2 min
2. Open master.blade.php layout line no 477 token time 1h
3. open master.blade.php-layout/front line no 535 token time 1h

After two minutes when we refresh the page session expired alert message not showing.
It should show an alert message so user can understand easily.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Still not showing developer looking on it.

**Review by SarfrazS — APPROVED** [review]
Now session expired alert message showing.
Note:- only in-store all page not expiry session

**Review by mverma16 — APPROVED** [review]

**Pull request closed without merging**
