### PR TITLE
Autoupdate ver 2

### PR DESCRIPTION
**Pull request by ashu555**
- Option for adding price for different country
-Widgets improve
- Faveo installation-path Api's updated
- Github bug fixes

Run
-php artisan migrate

-php artisan db:seed --class=PlanPriceSeeder

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
When we are hitting migration and seeder command on existing billing db throwing below error. Please may know why it's throwing.

image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Today I checked the plan module, once testing complete I will update here

**Review by SarfrazS — CHANGES_REQUESTED** [review]
What are the modules you explained we tested issues are there updated in below doc. 
Tomorrow we will continue the overall system and will update in the same doc.

https://docs.google.com/document/d/1j7FO7y9QpmR3151xkNL8dXm3EQbyoetmKQDFxCuPdnA/edit

**Review by SarfrazS — COMMENTED** [review]
Blocker issue please if u have time look into so that we can continue the overall system with live DB.
Step to reproduce:-
1. First I export live billing DB.
2. Imported in my local machine and changed default setting url.
3. Check out this branch
4. In the terminal when we hit the first command:-  php artisan migrate.

Getting below error alert message, Please may i know why itis showing.
image

When we hit the second command what you mention on pr php artisan db:seed --class=PlanPriceSeeder

image

After that hit url on the browser throwing the below error
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
**Issues:-** 
1. Login and registration required alert message not symmetric. for login showing a popup and for registration under field one by one showing
2. Retested all issues some are not fixed updated on doc.
3. Issue when we are creating a user from the user directory not receiving the password email.
4. In the register page country drop-down icon UI breaking.
5. Australian currency showing twice 
6. In the cart page, clear my cart button UI breaking not symmetric. 
7. When the user paying in USD in the invoice page showing INR. Please see the below
image
8. in the forgot page please show symmetric alert message color
image
9.  In create/edit plan page, should not allow adding two currency for the same country. it does not make any sense.

**Queries:-**
1. Why we are not able to open the Contact us Page without login?
2. suppose I click on the cart and in my cart no items are there showing continue to shopping once we click it is redirecting to login page but when we click on choose product why it's redirecting to login page

**Comment by SarfrazS** [comment]
Please check shruti's documentation and comments there so that she can retest after that she will remove from the doc. Most UI and validation related issues are there.

I also retested some issues created on GitHub based on your comments. please fix all the above issues let us know.
Thank You

**Review by shruti376 — CHANGES_REQUESTED** [review]
Please see the below document for issues and can comment once fixed 
https://docs.google.com/document/d/117BQe92b_UTtPogzAn8fD9msnlX_K1E0tjkwfkeWozI/edit

**Review by shruti376 — CHANGES_REQUESTED** [review]
Issues
1. Breadcrumb for Create Product not showing correct
2. In create new product, category field selected still showing required alert message
3. License type value get remove on creating product
4. Groups are not opening from store in client panel, showing 500 error
5. Sorting Arrows still showing in Actions

Please review the document below for screenshots
https://docs.google.com/document/d/117BQe92b_UTtPogzAn8fD9msnlX_K1E0tjkwfkeWozI/edit

**Review by shruti376 — COMMENTED** [review]
Retested all the pointed issues. All are fixed except one. Will retest once fixed

**Comment by SarfrazS** [comment]
@ashu555 Please once you remove anything from existing functionality, please let us know and also update on PR so all people will know about it.
Did you remove the Category field from the add product page why?

**Comment by ashu555** [comment]
> @ashu555 Please once you remove anything from existing functionality, please let us know and also update on PR so all people will know about it.
> Did you remove the Category field from the add product page why?
> image

Category did not have any funtionality in the system. So removed

**Review by SarfrazS — CHANGES_REQUESTED** [review]
I am checking on the server still not fixed, if you already fixed please comment here so that I can test on local.
New Issues:-
1. UI alignment is not showing properly for enterprise produce please look at the below gif.
ehd

2. When we are doing payment from the user's directory for the previous month, but in dashboard showing current month box. Please see the below gif
gif

3.  in India Telangana state not showing in the drop-down list.
4. Why this TinyMCE alert message showing while creating and edit the product. (in TinyMCE everywhere showing )
image
5. Unable to open the my-invoice page please see the below gif with login details and try it.
URL:- https://staging.billing.faveohelpdesk.com/my-invoices
username:- sarfraz password:- password
gif
6. If system email not configured or SMTP having any issue, User truing to forgot password getting below alert message which is not user friendly. 
image

7. User is logged in, now he moves the cursor on a cart and clicks on choosing a product, then it should redirect to the product page instead of my-invoice page
8. Open my order and click on renew based on product plan showing price but once we click on another product renew,  previous price showing. Please see in below gif
gif
9. License copied popup not showing once we click on copy. in live it is showing.
gif

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue No 7:- Please comment on this issue.
Issue No 9:- Not fix still looking at it.

Rest all issues fixed and working fine.

**Review by SarfrazS — APPROVED** [review]
All the above issues are fixed.

**Pull request merged**
