### PR TITLE
Making subtitle bold for Demo and Contact us page email template

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Old PR: #2928 
Run the following command:
php artisan db:seed --class="Database\Seeders\v4_0_2\DatabaseSeeder"

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Inconsistent issue 1:- when we send a message from the Contact Us page showing an attachment icon on a ticket and in the ticket thread showing as below.
image

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please comment and change the label how i will know whether you fixed it or not.

**Comment by sowmiyasubramaniyan** [comment]
@SarfrazS 
The issues you mentioned are related to Faveo. You can raise an issue for this in Faveo. Here, what we are doing is sending the mail content in the ticket. It's just picking the mail content from billing; other details are coming from Faveo. Therefore, you can raise an issue in Faveo for this.

**Comment by SarfrazS** [comment]
> @SarfrazS The issues you mentioned are related to Faveo. You can raise an issue for this in Faveo. Here, what we are doing is sending the mail content in the ticket. It's just picking the mail content from billing; other details are coming from Faveo. Therefore, you can raise an issue in Faveo for this.

May i know if you are saying this Faveo issue, please tell me to step i will also cross-verify.

**Comment by sowmiyasubramaniyan** [comment]
Please check the Faveo API using Postman with assistance from Faveo developers.

**Comment by SarfrazS** [comment]
> Please check the Faveo API using Postman with assistance from Faveo developers.

Tell me the developer's name.

**Comment by sowmiyasubramaniyan** [comment]
check with @sandesh556

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan i discussed this with @RafficMohammed  he said to tell to sowmiya connect with I will explain to her.

**Comment by SarfrazS** [comment]
Above issue still not fixed.

**Comment by indira15v** [comment]
**Testing summary**
Testing done and pointed issues are fixed once PR  open will approve

**Review by SarfrazS — COMMENTED** [review]
Pointed issues are fixed now working fine.
Screenshot 2024-04-22 213125
Screenshot 2024-04-22 213815
Screenshot 2024-04-22 220829

**Pull request merged**
