### PR TITLE
Exports and Add or Remove columns from the data tables

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Run :
php artisan migrate
php artisan db:seed --class="Database\Seeders\v4_0_2_1\DatabaseSeeder"

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by RafficMohammed — DISMISSED** [review]

**Comment by indira15v** [comment]
Round one testing summary
Tested this PR on the server instance 
Issue sheet :https://docs.google.com/spreadsheets/d/1aoG_KD0Fh7dCNpE0brpm9N9TRAVaK3-pVZrX8q4UROk/edit?gid=0#gid=0
Testing time :4.5 hours
Total number of issues: 9
Major:0
Minor:0
Critical:0
Is the PR breaking any functionalities? : NO
Number of times PR went for functionality correction: 1

**Comment by AbishekChinnaraju** [comment]
**Second Round testing summary**
I tested this PR on the server instance
Issue sheet :https://docs.google.com/spreadsheets/d/1aoG_KD0Fh7dCNpE0brpm9N9TRAVaK3-pVZrX8q4UROk/edit?gid=0#gid=0
Testing time :1Day
Total number of issues I found: 6
Number of times PR went for functionality correction: 1
**Note:**
- I tested only what the developer (suggested) fixed in Export and column options in All users, All Orders, All invoice modules only.

**Comment by indira15v** [comment]
While running the export command throws error
Screenshot from 2024-06-21 14-44-10

**Comment by indira15v** [comment]
Need to check with redis in server but cp7 server was down since yesterday once its ready will continue testing

**Comment by indira15v** [comment]
**Retesting summary** 
Tested this PR on the local and server with redis and database queue
1.Retested all the issues the mentioned issues are fixed and working fine 
2.Tested the export of users,orders,invoices with filter and cloud hub also 
3.Cloud hub was working fine in database and due to test server issue couldn't test with redis
Issue sheet :https://docs.google.com/spreadsheets/d/1aoG_KD0Fh7dCNpE0brpm9N9TRAVaK3-pVZrX8q4UROk/edit?gid=0#gid=0
Total number of issues: 3
Major:0
Minor:0
Critical:0
Is the PR breaking any functionalities? : NO
Number of times PR went for functionality correction: 2

**Review by indira15v — APPROVED** [review]

**Review by SarfrazS — APPROVED** [review]
I checked export functionality for users orders and invoice with queue as database working fine.
image

**Pull request merged**
