### PR TITLE
Validation for license url

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Issue fix : #1149 & #1914

### CODE REVIEW

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by RafficMohammed — APPROVED** [review]

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with existing db on server:**
Found issue there:

- [ ] In API keys > Auto Faveo Licenser & Update Manager, enter inavlid API URL and save. See error which are popping up
image

Query: For mentioned issue 
**It should accept only valid API secret key and API URL. If we accept invalid and save it then while view order throwing below error.** Throwing below error ----------- Is it fine?
image

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
- [ ] Unable to purchase the product if the product has a price. Even though, API key details are valid.

jan27ppur


- [ ] Unable to purchase the product if the product has a price. If API key details are Invalid. Showing below error message.

jan27pay


Note:

**Review by priyadarshini2101 — APPROVED** [review]
Pointed issues are fixed.

**Review by manikz5 — APPROVED** [review]
Tested PR, both issues are fixed.
After Fix : 
1. Now showing proper pop up message while buying prdoct with invalid api secret and url : 
apikey

2. Now pop-up messages for cloud details getting vanished after few seconds.

**Pull request merged**
