### PR TITLE
Redirection when user is log out

### LINKED ISSUE #2780: REDIRECTION OF LICENSE CODE URL
If user is sign out and clicks on the click here for license code ,it should ideally redirects to the same page where it redirects when its signed in that is(/public/my-order/{order_id})
image

### PR DESCRIPTION
**Pull request by Gurmeenkour99**
Fixes #2780

### CODE REVIEW

**Review by sandesh556 — CHANGES_REQUESTED** [review]
Why was all this removed

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Review by sandesh556 — DISMISSED** [review]

**Review by ganthimathin — CHANGES_REQUESTED** [review]
Verified this issue in local with existing DB. After checkout this branch, observed below issues:

1.UI alignment of the client panel is not looking good

 2.I am unable to purchase the free product. getting below error message.
3. When trying to pay for the product using stripe\razorpay exception throws.

image

image

image

**Comment by sandesh556** [comment]
Can we run the 306 seeder here and also see if all the migrations have run in the version

**Comment by Gurmeenkour99** [comment]
@ganthimathin  please refresh , check in development, i've tested ,it is working  
image

**Review by ganthimathin — APPROVED** [review]
Verified this issue in local with existing DB. 

Mentioned issue is fixed. While testing observed below thing.

After run the seeder command php artisan db:seed --class=Database\\Seeders\\v3_0_6\\DatabaseSeeder - the changes is not getting affected. The hyperlink for Click here option was missed. - Now it was fixed.

Calendar icon is not clickable in invoice page. - Issue exists in development branch as well . informed to developer.

**Comment by ganthimathin** [comment]
Round 1 Test Summary:
Total time in days:3 hours

Total issues: 1
Minor - 
Major - 1
Critical - 0

No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

**Comment by Sabaric12** [comment]
Round 2: Testing Summary
Tested this PR with the existing DB
The mentioned issues are working fine now
Now it can redirect to that particular order details page if logged in already otherwise going to the login page 
The hyperlink issue was also fixed
Total time in days: 2 hours
Total issues:0 
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

**Review by Sabaric12 — APPROVED** [review]

**Pull request merged**
