### PR TITLE
Pricing screen enhancement

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Old PR: https://github.com/ladybirdweb/agora-invoicing-community/pull/2286
issue: #1896 
Run the following command:
php artisan migrate
php artisan db:seed --class="Database\Seeders\v3_0_3\DatabaseSeeder"

### CODE REVIEW

**Comment by Dhayanan** [comment]
@sowmiyasubramaniyan Please resolve conflicts files 
image

**Comment by Dhayanan** [comment]
While creating the plans, it throwing the below error
image
image

Because of this issue I can't able to proceed testing, round one testing is not completed.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
**Major issue**:- User buying per month for 10 agents but they are getting license for 1 year.
image
image
image
**Minor Issue**:- Should not allow to put 200 percent in the offer price.
image
**Major Issue **:- Offer price calculation not working.
image
image
**UI Issue:** UI is breaking if the price is large.
image
image

**Minor Issue**:- While creating plans we are adding the number of agents. After that when we click on edit and then click on update we get the below alert message.
image
image
**Major Issue**: Price is showing differently on the checkout page.
image
image
**Minor issue**:- On the invoice page discount amount is showing wrong.(on pdf also)
image
Minor Issue:- When a user is not logged in and clicks on a group he gets the below error.
image
image
Major issue:- In the plan One Time not showing on the drop-down list.
image
Minor Issue:- per year should not show for one-time plan products. See below image how its showing
image
In this branch how it's showing
image
Minor Issue:- Change the pricing template image from the group.
Minor Issue:- Remove S from cart totals see in the below image.
image
image
Minor issue:- The Order Now button is not clickable because when mouse over on Order Now finger icon does not appear.
Addmedia

**Comment by DhanyaChengappa** [comment]
@Dhayanan Update this after testing


**First Round Test summary**
Total time in days:

Total issues: 
Minor - 
Major - 
critical -

**Comment by Dhayanan** [comment]
First Round Test summary
Total time in days:
Minor issue:-
1. While creating the plans, select the number of agents and click the save button. edit the plans, the set number of agents data is not showing.
issue1
2.Store >>product UI is breaking.
issuen12
3. Enabling the yearly toogle button, now product checkout to proceed, gets it's throwing below error.
image (19)

**Comment by SarfrazS** [comment]
First-Round Test Summary
Total time in days: 1.5 days

Total issues:13
Minor -9
Major -4
critical -0

**Review by SarfrazS — APPROVED** [review]
All Pointed issues are fixed. Working fine.
Last commits
image
Second Round Test summary
Total time in days: 0.5

Total issues:4
Minor -4
Major -0
critical -0

**Pull request merged**
