### PR TITLE
Bugfixes in Product Module

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Fix: #1972 
Bugs are elaborated in the below document with the module index as the Product.
https://docs.google.com/spreadsheets/d/1CB139UvzvUtB1JOHYP0nmEqjxdoHQPGWLGjD_niH9pw/edit#gid=1379931937

### CODE REVIEW

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with existing db on server:**
Found issues there:

- [ ] Click on edit product, getting below error
image

**Comment by sowmiyasubramaniyan** [comment]
> Checked with sowmiya's DB, mentioned issue working fine but in Sarfraz sir DB issue happening

Fixed

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by priyadarshini2101 — APPROVED** [review]
Tested the pr in server instance.

Pointed issues are fixed.

- [ ]  In the edit product, the selected image is not showing.

After fix
feb6pro

- [ ] When the plan is created or edited with a single plan, the UI is breaking.

After fix
feb6ui

- [ ]  Currency showing incorrectly in the All Plans list and the Price displaying as Not Available.

After fix
feb6ui1

- [ ] In the Product edit, For a few milliseconds, the description shows the HTML script and then updated the content.

After fix
feb6ui2

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:- While creating new periods from plan popup and then creating plans with new periods getting below error.(it's happening only first time)
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Still not working functionality properly Please fix it and update me. On the edit plan page periods and months value not showing correctly.
image
image

**Review by SarfrazS — APPROVED** [review]
Pointed issue fixed now

**Pull request merged**
