### PR TITLE
S3 file storage

### PR DESCRIPTION
**Pull request by sadhasivam-ladybirdweb**
### Issue: #3095 

Previous PR accidentally closed : https://github.com/ladybirdweb/agora-invoicing-community/pull/3130

# Run the following commands:

```bash
php artisan migrate
php artisan db:seed --class="Database\Seeders\v4_0_2_3\DatabaseSeeder"
```

### CODE REVIEW

**Comment by indira15v** [comment]
**Round one testing summary**
Tested this PR with existing db and fresh installation
**Issue sheet**
https://docs.google.com/spreadsheets/d/1_W7QmEQKyIE09D7ypMC1_rv3f3PTQAsurngbf2posvI/edit?gid=0#gid=0
Total issues :11
**Note :**
@sadashivam please get code approval

**Comment by SarfrazS** [comment]
@sadhasivam-ladybirdweb what is the status and when should it be ready for retesting?

**Comment by sadhasivam-ladybirdweb** [comment]
> @sadhasivam-ladybirdweb what is the status and when should it be ready for retesting?
Related issues have been fixed. Some issues are unrelated but need to be addressed later. For retesting, we need to raise a PR in the license manager before starting the testing.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
**Blocker issue please check and let me know.** we can't continue testing.
Issue:- I was done fresh installation on my local wamp server. After configured s3 Instance stop working. in logs getting below error.
image
image

**Comment by SarfrazS** [comment]
> **Blocker issue please check and let me know.** we can't continue testing. Issue:- I was done fresh installation on my local wamp server. After configured s3 Instance stop working. in logs getting below error. image image

**Below s3 details I configured which are not available that's why the instance is not working. We have to put validation. In faveo these details not accepting.**

AWS_SECRET_ACCESS_KEY=65f04692af1cacb254f8dc198e40e7ce
AWS_ACCESS_KEY_ID=6f5c6269c43b0ee9d03d963df1bead83
AWS_DEFAULT_REGION=usc1
AWS_BUCKET=lws-test-public
AWS_ENDPOINT=https://usc1.contabostorage.com/
AWS_URL=https://usc1.contabostorage.com/eec046afcbc84333a334b9211c82a409:lws-test-public
AWS_USE_PATH_STYLE_ENDPOINT=true

**Review by sandesh556 — APPROVED** [review]

**Comment by sadhasivam-ladybirdweb** [comment]
The blocker issues have been fixed, we can now proceed with testing.

**Comment by SarfrazS** [comment]
What about the MariaDB port 3307 installation issue? Have you fixed it? In the master branch, it was working fine.

**Comment by SarfrazS** [comment]
Issue 1:- while installing agora invoicing with port no. installed put port not picking.
image
Issue2:- After configured s3,  unable to upload the helpdesk zip file on Agora.
image

**Comment by sadhasivam-ladybirdweb** [comment]
Please create a separate issue for the existing one. This is a high-priority issue and needs to be finished quickly.

**Comment by AbishekChinnaraju** [comment]
**Round one testing Summary:**
I tested this PR in the local existing DB.
Total testing time: 2.5 days
Total no.of issues I found along with query (Both this PR and dependency PR): 11
**Note:**
- I tested the storage path of uploaded files in this PR and verified whether the auto-update is working fine in the dependent PR.
-I used the S3 credentials provided by the developer from the DigitalOcean server.
- I created Separate issues for existing and approved this PR under developer guidance.

**S3 Storage path:**

Screenshot from 2024-11-23 11-31-33

**Uploaded file in Digital Ocean server:**

oceanbay s3

**Review by AbishekChinnaraju — APPROVED** [review]

**Comment by indira15v** [comment]
**Round one testing summary:**
Tested this PR in the existing local DB
Total testing time: 2.5days
**Note** 
1.Tested the storage path of uploaded files(both system and S3) in this PR and verified  auto-update in the dependent PR
2.Used S3 credentials provided by developer and server team
3.Created separate issues for existing as discussed with developer and approved this PR 
**Issue sheet**
https://docs.google.com/spreadsheets/d/1_W7QmEQKyIE09D7ypMC1_rv3f3PTQAsurngbf2posvI/edit?gid=0#gid=0
**Separate issue link**
https://github.com/ladybirdweb/agora-invoicing-community/issues/3147

**Review by indira15v — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
I am still checking and will update the issue here once testing is done, I will change the label.

1. S3 details don't save in DB; they save only on .env.(In faveo, we save only on .env, and in DB, we change from system s3; that's it.)
2. In Agora i configured contabo s3 details and in LM configured digital s3 details after that auto-update is not working.
3. I configured contabo s3 details in the agora and in LM after that also auto-update is not working.

Note:- Not getting any error in the network see in the below image.
image

**Comment by SarfrazS** [comment]
A secret key field is missing in the LM setting so the developer is working on it, once the developer is done and will start retesting.

**Comment by AbishekChinnaraju** [comment]
**Retesting Summary:**
- It does not navigate automatically after the auto-update is completed, it only works with a manual refresh.

**Comment by indira15v** [comment]
**Retesting Summary**
Lang issue occurs after autoupdating then after refreshing it redirects to the instance page

**Review by SarfrazS — COMMENTED** [review]
In dedicated server faveo instance s3 is not working i asked server team they said i have to check, anything is blocking on our network that's why not working. So i tested with system and it working fine. 
image

Note:- One scenario i am verifying after that will approve it.

**Comment by SarfrazS** [comment]
@Sadhasivam Sekar I have one query please can you explain to me how below scenario will work:-
Step1:- Agora setting is system.
Step2:- Uploaded faveo files with the below version
Step3:- v9.2.3 restricted, v9.2.3 Official, v10.0.0,v10.0.1
Step4:- Agora setting changed to s3.
Step5:- uploaded faveo file v9.3.0 official.
Step6:- Run check update command
Client using 9.2.2 version, what versions should display for the client?

In this scenario, auto-update is not working because the current setting is s3, and restricted files are uploaded to the system.
The developer saying we have to upload all files with s3 then only auto-update will work.

**Comment by SarfrazS** [comment]
Finally, I tested auto-update with s3 on a dedicated server and it works fine.
image

**Comment by sandesh556** [comment]
> @sadhasivam Sekar I have one query please can you explain to me how below scenario will work:- Step1:- Agora setting is system. Step2:- Uploaded faveo files with the below version Step3:- v9.2.3 restricted, v9.2.3 Official, v10.0.0,v10.0.1 Step4:- Agora setting changed to s3. Step5:- uploaded faveo file v9.3.0 official. Step6:- Run check update command Client using 9.2.2 version, what versions should display for the client?
> 
> In this scenario, auto-update is not working because the current setting is s3, and restricted files are uploaded to the system. The developer saying we have to upload all files with s3 then only auto-update will work.

You can't  just switch s3, and expect it to work on a whole. Every time the storage is switched the contents has to be moved to that storage for it work fully.

**Review by SarfrazS — APPROVED** [review]
Download and autoupdate working fine with system and s3.

**Pull request merged**
