### PR TITLE
Removes mobile number numeric validation to keep consistency

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
resolves https://github.com/ladybirdweb/agora-invoicing-community/issues/1984

There are several ways we could get this exception for example:

An empty string is NOT numeric
Space between mobile number is NOT numeric
Contains any special characters in mobile number is NOT numeric

In php 7
'123456789 ' is NOT numeric

Generally It is not advisable to use numeric in phone numbers.

### CODE REVIEW

**Comment by sowmiyasubramaniyan** [comment]
Old P.R : https://github.com/ladybirdweb/agora-invoicing-community/pull/2116

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with existing db on server:**
Facing issue there

- [ ] Email/Mobile confirmation page loading continuously 
image
While inspecting getting below error
image
ing getting below error

Not able to proceed with testing due to this issue. Once issue fixed will continue testing

**Review by Sheetal34 — COMMENTED** [review]
Mentioned issues are fixed but facing another issues. Need to discuss

**Review by Sheetal34 — APPROVED** [review]
**Tested with existing db on server:**
Mentioned fixes working fine. Checked for other scenarios also.Working fine

**Review by SarfrazS — APPROVED** [review]
Now only accepting valid 4-digit opt what Agora sent on mobile once we entered the correct opt then only mobile get verified.
image
image

**Pull request merged**
