### PR TITLE
Release-2.0.0

### PR DESCRIPTION
**Pull request by sandesh556**

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
@sowmiyasubramaniyan please can you check why this error we are getting.
image

**Comment by sandesh556** [comment]
Seems like a permission issue.

**Comment by sandesh556** [comment]
@SarfrazS i have pushed the fix, pull again

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:- Installation path not showing in order page. (client and agent panel)
image

**Review by SarfrazS — APPROVED** [review]
Except cloud i checked all functionality it's working fine.
I checked Agora+LM+faveo (installation License and products integration) working fine.

**Pull request merged**
