### PR TITLE
Client panel theme update

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Run the following command:
php artisan migrate
php artisan db:seed --class="Database\Seeders\v3_0_6\DatabaseSeeder"

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Please fix below sheet issues parallelly  i will update all issue here. 
https://docs.google.com/spreadsheets/d/1btEGNHWjSNNF0CK6PjdOyYQ5bRG22QomMezOI0BGIjo/edit#gid=0

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Major issue:-Unable to purchases any product getting below error.
image
Note:- Pointed issues also not fixed.

**Comment by sowmiyasubramaniyan** [comment]
> Major issue:-Unable to purchases any product getting below error. image Note:- Pointed issues also not fixed.

This is an existing issue and also please mention on the same sheet which issue is fixed and which is not.

**Review by manikz5 — CHANGES_REQUESTED** [review]
Testing PR, below are the issues found, testing is not completed yet
https://docs.google.com/spreadsheets/d/1LrC4kllgXNE0JO7IgZ4V_xU0nL7BdckJ6u5JiisguvI/edit#gid=0

**Review by manikz5 — CHANGES_REQUESTED** [review]
Please fix pointed issues as mentioned in sheet and shown in GIF below:
1. Overlapping of product description and button.
2. Loader placement is not fixed while using "+" and "-" on cart page.
3. Able to decrease agents to -ve value as shown in GIF.
4. Fix retire.js security issues.
5. Please make page title font little less and equal on all pages, and reduce border too as too much white spacing is there.
6. Product remove icon should be placed away from product image and aligned with the text, and if no image selected for product it should remain blank instead of broken image icon. For reference please check the screenshot attached.
issue12

image322

**Review by manikz5 — CHANGES_REQUESTED** [review]
Checked pointed issues are fixed except retire.js vulnerabilities still showing on few pages "my order" , " checkout",...
image

image

**Review by manikz5 — CHANGES_REQUESTED** [review]
Unable to proceed further, button is not clickable on place order page:
image

**Review by manikz5 — CHANGES_REQUESTED** [review]
For ubuntu screen preview is not aligned properly with default system settings and browser screen size 100%, for reference see below screenshot:
image

**Review by manikz5 — DISMISSED** [review]
Mentioned issues are fixed, and with default page it is working fine.
image

**Review by SarfrazS — APPROVED** [review]
Pointes Issues are fixed working fine.
Note:- Cloud functionality i didn't test Because Sandesh told me cloud functionality you can test in my pr.

**Pull request merged**
