### PR TITLE
Installation status update

### PR DESCRIPTION
**Pull request by sadhasivam-ladybirdweb**
This PR is dependent to the license manager PR : https://github.com/ladybirdweb/agora-license-manager/pull/259

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by RafficMohammed — DISMISSED** [review]

**Comment by AbishekChinnaraju** [comment]
@sadhasivam-ladybirdweb please get clarity regarding the functionality and issues you fixed.

**Comment by AbishekChinnaraju** [comment]
**Round one testing summary**
Tested this PR with the local instance
Total issues:0
Minor - 0
Major - 0
Critical - 0
No of times PR sent for Functionality correction:0
PR breaks existing functionality: No
**Note:**
- Now the installation status details are updated as per the installation logs' updation in the License Manager.

**Review by SarfrazS — APPROVED** [review]
working fine.

**Comment by indira15v** [comment]
Testing summary
This is linked with license manager and its working fine

**Review by indira15v — APPROVED** [review]

**Review by AbishekChinnaraju — APPROVED** [review]

**Pull request merged**
