### PR TITLE
Template seeder changes

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
old P.R: https://github.com/ladybirdweb/agora-invoicing-community/pull/2404
run the following command
php artisan db:seed --class="Database\Seeders\v3_0_3\DatabaseSeeder"

### CODE REVIEW

**Comment by sowmiyasubramaniyan** [comment]
@SarfrazS please start testing this PR.@bhanu2217 sir approved the demo.

**Comment by DhanyaChengappa** [comment]
@Gurmeenkour99 Please give a demo for this before you raise a PR

**Review by SarfrazS — APPROVED** [review]
Tested with existing db new template seeder is working fine.
We received all mails from templates

Note:- once conflicts resolved will change the label.

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan If you rebased from development then please resolve conflicts and let me know.

**Pull request merged**
