### PR TITLE
Release-402

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Run :
php artisan db:seed --class="Database\Seeders\v4_0_2\DatabaseSeeder"
Fixes:
       

- [ ]     #2876 
- [ ]            #2883 
- [ ]            #2136 
- [ ]            #2900 
- [ ]            #2901
- [ ]            #2909 
- [ ]            #1897
- [ ]            #2897 
- [ ]            #2925
- [ ]            #2922 
- [ ]            #2889 
- [ ]            #2927
- [ ]            #2880 
- [ ]            #2858

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
@sowmiyasubramaniyan Please link all the issues on release build pr.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:- I ran database sync command but still template content not changed.
image

**Comment by sowmiyasubramaniyan** [comment]
> Issue:- I ran database sync command but still template content not changed. image


@SarfrazS here nothing will change
Screenshot from 2024-04-30 10-10-15

Click on edit, here you need to check

**Comment by sowmiyasubramaniyan** [comment]
> Issue:- I ran database sync command but still template content not changed. image

Fixed

**Comment by SarfrazS** [comment]
Issue:- While adding files on products, the UI is breaking, and unable to add it.
image

**Review by sandesh556 — APPROVED** [review]

**Review by SarfrazS — APPROVED** [review]
**Final Round Testing Summary:**
I tested release build on existing server instances.
Testing time : 4 Days
Total number of issues: 10
Major:0
Minor:10
Critical:0
Is the pr breaking any functionalities? : NO
Number of times went for functionality correction: 2
Tested with Below Stipe test card.
India, Australia, Canada, Brazil, Namibia, China ete..(visa/mastercard)
Tested with below Razorpay test card.
Visa card domestics/International 
Master card  Domestic/International.
image

Note:- Tested Stripe  payment gateway with live card

**Pull request merged**
