### PR TITLE
Installation path issue

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Old PR: #2924

### CODE REVIEW

**Review by RafficMohammed — APPROVED** [review]

**Review by sandesh556 — APPROVED** [review]
Code seems fine, But i want a demo for integration

**Comment by SarfrazS** [comment]
Yesterday sandesh explained what the issue here,  before she didn't know. without knowing I don't what she has fixed.

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please check and reopen the pr

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:- Installation path not showing on order view page.
Step to replicate:-
1. Install first instance after that click on reissue license.
2. Install second instance. it is showing.
3. Again install third instance not showing overview page.
image
image

Note:- On the license manager installation data table shows 2 installations as well as on the callback data table both instance are showing.
image
image

For Refre:-
https://qa.productdemourl.com/saifzip/public/panel/dashboard
https://qa.faveodemo.com/sarfrazsd/public/panel/dashboard

**Comment by sowmiyasubramaniyan** [comment]
@SarfrazS sir you did not change the billing URL in the apl_core_functions.php
that's why it's not showing in the billing 
please recheck again

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan installation why showing twice in the license manager installation table?
image

**Comment by sowmiyasubramaniyan** [comment]
> @sowmiyasubramaniyan installation why showing twice in the license manager installation table? image

@SarfrazS check in master, If it is an issue, please create an issue in the license manager

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:- From license manager i made it inactive but in agora still showing active.
image
image

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please fix the two above issues and let me know,  after that will retest and approve it.
1. Version issue.
2. Active issue

**Comment by indira15v** [comment]
Issue 
When entered the license code the login page throws 500 error 
Screenshot from 2024-04-24 14-48-28

**Comment by indira15v** [comment]
Query
Status was still shown active when deleting the  env file and making database clear,and when try to install it installs
In license manager also status was shown as active in installation
Screenshot from 2024-04-24 15-00-09

**Review by SarfrazS — APPROVED** [review]
The pointed issues are fixed. Now working fine.
image
image

**Comment by indira15v** [comment]
**Testing summary**
The pointed issues are fixed and working fine now

**Review by indira15v — APPROVED** [review]

**Pull request merged**
