### PR TITLE
Seeders with Version

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Do check in the fresh installation.
Should migrate the all tables and run all the seeders.

### CODE REVIEW

**Review by ajaz-ul-haq — APPROVED** [review]

**Review by RafficMohammed — DISMISSED** [review]

**Comment by Sheetal34** [comment]
@sowmiyasubramaniyan Please tell me what we need to test in this pr, complete billing functionality or what?

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with fresh installation on server:**

- [ ] Click on API Keys, getting below error
image

For this issue, I have raised a separate PR.

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
Checkout to pr branch with fresh Installation , Unable to continue Installation with this branch facing below error.

feb3af

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
Checkout to pr branch with fresh Installation , Unable to continue Installation with this branch facing below error.

feb7error

**Review by priyadarshini2101 — DISMISSED** [review]
Tested the pr in server instance

Pointed issue fixed.

Now the tables are migrating.....

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Please show the proper message or you can make it hide **API key** Module and give the tooltips. From the user's perspective, this alert message is not acceptable.
image
Issue 2:- In-country list only shows one country.
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue no2 still Not fixed.

**Comment by sowmiyasubramaniyan** [comment]
> Issue no2 still Not fixed.

It is not an issue. Explained to @SarfrazS sir

**Review by SarfrazS — APPROVED** [review]
Developer told me not an issues based user country list will show.

**Pull request merged**
