### PR TITLE
Billing Refinements

### PR DESCRIPTION
**Pull request by sandesh556**
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2357
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2359
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2355
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2351
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2344
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2349
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2350
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2367
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2348
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2358
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2212
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2354
- [x] https://github.com/ladybirdweb/agora-invoicing-community/issues/2375
- [x] #2379
- [x] #2352
- [x] #2341

### CODE REVIEW

**Comment by bhanu2217** [comment]
@sandesh556 can we connect, if you can give me demo of the changes done and take my feedback for the same?

**Comment by sandesh556** [comment]
> @sandesh556 can we connect, if you can give me demo of the changes done and take my feedback for the same?

Will let you know, I need a cloud development environment to test a few things in this PR, Then we can connect. Will Ask thiru to start with it today when he's available

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Review by SarfrazS — APPROVED** [review]
All Above pointed issues are fixed.
Note:- Horizon issue not working here Sandesh told me we cant check here will check on live.

**Comment by sandesh556** [comment]
Not live but need to be checked in this PR https://github.com/ladybirdweb/agora-invoicing-community/pull/2372

**Comment by bhanu2217** [comment]
Please give demo to me for this P.R or install it on CP7 and share the URL and credentials.

**Comment by sandesh556** [comment]
The demo is already given. We will have another beta testing round during the final build

**Pull request merged**
