### PR TITLE
Search Functionality Bugs

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Fix: #2369

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by RafficMohammed — APPROVED** [review]

**Comment by bhanu2217** [comment]
Advance filter by default should be closed 1st time.
Rest looks good. Approving demo

**Review by SarfrazS — CHANGES_REQUESTED** [review]
When we open order invoice and users advance search open. please see in below image. Rest are fixed.
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue1:- In user advance search date picker is not vanish/hidding when we click on outside.
image
Issue2:- In All advance search, Advance search is open but it is showing + icon instead of -
image

Issue3:- In all Advance search when we click on reset advance search getting closed instead of open and values should reset from advance search.

**Comment by sowmiyasubramaniyan** [comment]
> Issue1:- In user advance search date picker is not vanish/hidding when we click on outside. image Issue2:- In All advance search, Advance search is open but it is showing + icon instead of - image
> 
> Issue3:- In all Advance search when we click on reset advance search getting closed instead of open and values should reset from advance search.

Fixed

**Review by SarfrazS — DISMISSED** [review]
Pointed issues are fixed now working fine.

**Review by Sabaric12 — DISMISSED** [review]
Tested this Pr with the Fresh Installation
The mentioned issues are fixed now

**Pull request merged**
