### PR TITLE
Alignment fixes in Cart page

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**

### CODE REVIEW

**Review by ajaz-ul-haq — APPROVED** [review]

**Review by laksh-22 — APPROVED** [review]

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
Changes not reflected while giving demo

**Review by Sheetal34 — APPROVED** [review]
**Checked with existing db on server:**
Mentioned issues are fixed

- Icons are not showing in breadcrumb in the Checkout page 
Before fix:
image
After fix:
image

- Alignment and gap issue in stripe image on the checkout page
After fix:
image

- Alignment issues on the cart total grid and the button on the Checkout page
After fix:
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Please reduce the space between radio button and stripe. it's not intuitive. you can take others feedback.
image

**Comment by sowmiyasubramaniyan** [comment]
That is an image. Currently, "Razorpay" includes an icon missing in "Stripe".

**Review by SarfrazS — APPROVED** [review]
Got it Rest pointed issues are fixed.

**Pull request merged**
