### PR TITLE
Fixes of twitter and tawk chat issues

### LINKED ISSUE #2813: Twiiter Script Tag Issue
Tawk Chat is not working if user is not entering the script tags around the script.

### PR DESCRIPTION
**Pull request by Gurmeenkour99**
Working of tawk chat
fixes #2813

### CODE REVIEW

**Comment by Gurmeenkour99** [comment]
previous Pr https://github.com/ladybirdweb/agora-invoicing-community/pull/2812

**Review by sandesh556 — DISMISSED** [review]

**Review by ajaz-ul-haq — DISMISSED** [review]

**Comment by Sabaric12** [comment]
Round 1: Testing Summary
Tested this PR with the existing local instance 
The mentioned issues are working fine now
Total time in days: 1 hours
Total issues: 0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

**Review by Sabaric12 — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
@Gurmeenkour99 I need a demo for tawk chat issue. After that i will start testing.
In Agora where do we have a department?
image

Tooltips also not user friendly
image

**Comment by DhanyaChengappa** [comment]
@Gurmeenkour99 Why did this go to testing team without demo approval?
The UI is of extremely poor standards. Alignments are off, language is incorrect. Very poor standards.

**Comment by bhanu2217** [comment]
@SarfrazS as discuss Twak UI we have no control over.
@Gurmeenkour99 issues pointed towards things which are inside Tawk UI, please ignore them

**Comment by Gurmeenkour99** [comment]
@SarfrazS, as discussed, the tooltip color correction has been completed.

@DhanyaChengappa, this PR is a replica of my previous PR (https://github.com/ladybirdweb/agora-invoicing-community/pull/2812) that has the label "demo approved."

**Comment by SarfrazS** [comment]
> @SarfrazS, as discussed, the tooltip color correction has been completed.
> 
> @DhanyaChengappa, this PR is a replica of my previous PR (#2812) that has the label "demo approved."

It still shows the same tooltip color and has not changed
image

**Review by SarfrazS — APPROVED** [review]
Pointed issue is fixed, now working fine.
image

**Pull request merged**
