### PR TITLE
Auto renewal

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
This P.R is about Auto payment
1. Initially purchase the product, when the product subscription ends it will automatically credit the amount from the
customer and will send the email notification
2. If the Auto payment fails, we will send the Failed mail notification with the right message and an Auto reminder will send
the notice to make the manual payment. If the customer doesn't renew after a day again will try the autopayment.

Auto Reminders,
1. Email Reminders for Auto and Manual payments, Before and after product expiry.
2. Option to enable and disable Auto subscription in both client and Admin panels.

**Detailed Document:**
https://docs.google.com/document/d/1d97IZzufbsoFHZyS8mg6S9nOjZI2eP5aAVHKwC06nPY/edit#heading=h.622u64wbkry1

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] Issue1:- By default Auto-Renewal toggle is not enabled for the new invoice.
- image
- [ ] Issue2:- On Auto-renewal page only shows the actual price instead of the renewal price.
- image
- [ ] Issue3:- On the auto-renewal payment log data table status and expiry date showing wrong.
image
- [ ] Issue4:- On auto-renewal payment log data table not required a view option under the action column. Because when we click on it. it's redirecting to the order view page.
image
- [ ]Issue5:-  Auto-Renewal is enabled and the order gets expired. Now auto-renewal cron executing but not create a new invoice with successful payment.
- [ ] issue6:-  Auto-Renewal is enabled and the order gets expired. Now auto-renewal cron executing but not create a new invoice with successful payment as well as a client not receiving failure mail.
- [ ] Issue7:- From the auto-renewal page when we do auto-renewal manually by clicking the make payment option, we get the below error.
image
- [ ] Issue8:- Auto-renewal is enabled, Updated end at and support end at date got expired, and then renewal cron executed after that auto-renewal status is not changing.
image
image
image


Testing is not completed Please fix the above issue so that I can continue testing forward.

**Review by SarfrazS — COMMENTED** [review]
Issue1:- We purchased a product with a stripe payment gateway. After expired my subscription Autopayment was done for renewal but the price calculation is showing wrong in the stripe payment.
image
Issue2:- When our Autopayment has failed client receives failed mail. from that mail when the client clicks on make payment it's not redirecting to the cart page. And the price also showing wrong as well as failure reason is also not correct.
image
Issue3:- When our Autopayment has failed client receives failed mail. from that mail when the client clicks on renew order it's not redirected to the cart page. And the price also showing wrong as well as failure reason is also not correct.
image
Issue4:- lang file missing on template module.
image
Issue5:- Taking the latest renew date for all invoices as well as order no also not showing.
image
 
Query:- for user showing make payment and for admin showing renew the order. why? you can see on the above screenshot.

**Comment by sowmiyasubramaniyan** [comment]
@SarfrazS Issue no 5 & 8 is not an issue. Rest all issues I've fixed.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Still auto-renewal not working with razorpay. Connected with developer.she is looking on it.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Issue:-Still Auto renewal is not working with USD.
Issue:- user Currency is USD, Still while updating card details, on Razorpay showing INR.

**Review by SarfrazS — APPROVED** [review]
Auto-Renewal working fine with Stripe payment gateway only.
image
image
image

**Pull request merged**
