### PR TITLE
Release 3.0.1

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**

### CODE REVIEW

**Review by SarfrazS — COMMENTED** [review]
Just now i started final build testing whatever i find issue will update here. Please check and fix it.

- [ ] I Have done fresh installation on my local server, after that i click on cart button throwing below error.
image

- [ ]

**Comment by sowmiyasubramaniyan** [comment]
All issues are fixed.

**Comment by SarfrazS** [comment]
Thank you, Tomorrow i will retest and then approve it.

**Review by SarfrazS — APPROVED** [review]
Pointed issues are fixed Now working fine in fresh db also.

**Pull request merged**
