### PR TITLE
Password reset link and Session Logout

### PR DESCRIPTION
**Pull request by sadhasivam-ladybirdweb**
### Bug Fixes

- After updating the password from the profile, the previously sent reset link is now marked as expired.
- Added validation for all password fields.
- If the password is changed, other logged-in sessions of the same user are automatically logged out.

### Issue: #2814

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by RafficMohammed — DISMISSED** [review]

**Review by laksh-22 — APPROVED** [review]

**Comment by AbishekChinnaraju** [comment]
**Round two testing summary:**
I tested this PR on my existing local instance with less data.
Total testing time: 3.5 hrs
Total no.of issues along with query: 10
Total no.of issues I found along with query: 5
issues sheet: https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0

**Comment by Sabaric12** [comment]
Round one testing summary:
I tested this PR on my existing local instance with less data.
Total time in days: 2 days
Total issues:5 
Minor - 5 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No
Total no.of issues I found: 5
The issue sheet is mentioned below
issues sheet: https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0

**Comment by Sabaric12** [comment]
Round one testing summary:
I tested this PR on my existing local instance with less data.
Total time in days: 5 hours
Total issues:7
Minor - 5
Major - 2
Critical - 0
No of times PR was sent for Functionality correction:2
PR breaks existing functionality: No
Total no.of issues I found: 7
The issue sheet is mentioned below
issues sheet: https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0

**Comment by AbishekChinnaraju** [comment]
Re-testing summary:
I tested the mentioned issues, and a few of the issues need to be fixed.
Issue sheet: https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0

**Comment by Sabaric12** [comment]
Round one testing summary:
I tested this PR on my existing local instance with less data The mentioned issues are working fine now.
Total time in days: 4 hours
Total issues:7
Minor - 7
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:2
PR breaks existing functionality: No
Total no.of issues I found: 7
Note:
**https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0
Some existing issues were discussed with the developer, and a separate issue was created.
https://github.com/ladybirdweb/agora-invoicing-community/issues/3121**

**Review by Sabaric12 — APPROVED** [review]

**Comment by AbishekChinnaraju** [comment]
**Re-testing Summary:**
I tested the mentioned issues in this retesting round, and they are working fine. For a few issues, the developer suggested creating them separately, so I’ll create separate issues for those.
Issue sheet: https://docs.google.com/spreadsheets/d/1-nbp8cXeEqEwX_YWWaFETw_BodO-zaWi-hk1gC7C9m0/edit?gid=0#gid=0

**Review by AbishekChinnaraju — APPROVED** [review]

**Pull request closed without merging**
