### PR TITLE
text on array

### LINKED ISSUE #2745: Attempt to read property "text" on array
Error log : Exception: Attempt to read property "text".

### PR DESCRIPTION
**Pull request by Gurmeenkour99**
Fixes #2745 
         #1958 
         #2580 
         
  
Resolved the error log  "read property  text  on array"

### CODE REVIEW

**Comment by bhanu2217** [comment]
This P.R only resolves the error log issue. It doesn't fix broader issue of tweets working. We can merge this P.R but over all to get twitter working is also important.
If we cannot get twitter working, best is to remove this functionality.

**Comment by Gurmeenkour99** [comment]
I'll start checking with twitter issue

**Review by sandesh556 — APPROVED** [review]

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Comment by Sabaric12** [comment]
Round 1: Testing Summary
Tested this PR with the Server instance and the local instance the mentioned issue is working fine now
Before Fix:
 image
 image
 After Fix:
 image
Total time in days: 2 hours
Total issues: 0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

**Review by Sabaric12 — DISMISSED** [review]

**Review by SarfrazS — COMMENTED** [review]
please remove twitter and let me know then i will retest once again.

**Comment by SarfrazS** [comment]
@Gurmeenkour99 in 404 page why we are my invoice order profile contact us. see in below image
image

**Comment by Gurmeenkour99** [comment]
@SarfrazS Please check in master ,this is 404 page design , if you have any issue regarding this page please raise a separate issue for this.In this PR I have fixed the error "get text on null" and removed twitter API . if the API is not there it will redirect you to the 404 page .

**Comment by SarfrazS** [comment]
> @SarfrazS Please check in master ,this is 404 page design , if you have any issue regarding this page please raise a separate issue for this.In this PR I have fixed the error "get text on null" and removed twitter API . if the API is not there it will redirect you to the 404 page .

See here how it showing in the master branch where is a 404 page design
image

**Comment by SarfrazS** [comment]
> @Gurmeenkour99 in 404 page why we are my invoice order profile contact us. see in below image image

Are you fixing this issue or not tell,  Please don't do half of the things. If you are showing 404 then why you my invoice order profile contacts are showing?

**Comment by Gurmeenkour99** [comment]
@SarfrazS in development the page you are in is the error page that means when  something went wrong and the 404 page means when the page does not exists where we have to redirect when the url does not exists. both the pages are different.

**Comment by SarfrazS** [comment]
> @SarfrazS in development the page you are in is the error page that means when something went wrong and the 404 page means when the page does not exists where we have to redirect when the url does not exists. both the pages are different. Ok if i'm redirecting it to 404 that means the user hits some invalid url that means the url does not exists , then what is wrong if we give some useful links where it can go , it can be a guide for user. Also this is the part of theme .



> @SarfrazS in development the page you are in is the error page that means when something went wrong and the 404 page means when the page does not exists where we have to redirect when the url does not exists. both the pages are different. Ok if i'm redirecting it to 404 that means the user hits some invalid url that means the url does not exists , then what is wrong if we give some useful links where it can go , it can be a guide for user. Also this is the part of theme .

Redirecting to the 404 page is correct, My concern, if a user is not logged in and they are passing the wrong URL then why we are showing my invoice, my order, and my profile?

**Review by SarfrazS — APPROVED** [review]
I discusssed with @DhanyaChengappa  Maam,  she told me it's fine for now will think later for unauthenticated user.
image
pointed issues are fixed.

**Pull request merged**
