### PR TITLE
Fixes of twitter and tawk chat issues 

### LINKED ISSUE #2813: Twiiter Script Tag Issue
Tawk Chat is not working if user is not entering the script tags around the script.

### PR DESCRIPTION
**Pull request by Gurmeenkour99**
1. Added a tooltip to guide end users how to enter tawk script. Also handling if the user does not enter script tags.
2. Remove the Allow tweets dropdown from the admin_panel>>settings>>footer>>twitter

Fixes #2813

### CODE REVIEW

**Comment by DhanyaChengappa** [comment]
Demo feedback

- [ ] Add question mark for tooltip

**Review by sowmiyasubramaniyan — DISMISSED** [review]

**Review by sandesh556 — APPROVED** [review]

**Comment by Sabaric12** [comment]
Round 1: Testing Summary
Tested this PR with the existing instance 
The mentioned issues are not working and conflicts are also there
Total time in days: 
Total issues: 1
Minor - 0 
Major - 0 
Critical - 1
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

**Comment by Gurmeenkour99** [comment]
closing it as i'm doing all the changes in new pr https://github.com/ladybirdweb/agora-invoicing-community/pull/2843

**Comment by SarfrazS** [comment]
@Gurmeenkour99 PR got closed please check why it's closed and reopen it. I need a demo for Twak.

**Pull request closed without merging**
