### PR TITLE
RELEASE V3.0.3

### PR DESCRIPTION
**Pull request by sandesh556**

### CODE REVIEW

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please add all the issues here so that we can test all

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Critical issue:- While purchasing any products getting below error.
image
image

Major Issue:- Again price is showing wrong please check it.
image
image
Minor Issue:- Update from master to this branch one time showing twice picking periods and description.
On live
image

image
Minor issue:- Suspended user not able to delete getting below error 
image
Major Issue:- On the cloud instance, and normal instance php with redis, mails are not sending getting the below error on the pending job.
image
image

Major issue:- In the user data table under registered on a column showing as below.
image
Major Issue: In one day 729 errors log on email log.
image
Minor issue:- When we open email log profile image not showing.
image
image

**Comment by sandesh556** [comment]
Keys for live license managers are updated. Check live billing and change it here also

**Comment by sandesh556** [comment]
@SarfrazS are all these issues resolved?

**Comment by SarfrazS** [comment]
No, till Yesterday 7:30 PM not resolved at all.

**Review by SarfrazS — APPROVED** [review]
All pointed issues are Fixed Now.
Second Round Testing Summary in Final Build.
No of days:- 3 days
Major Issues: 8
Minor Issues: 5
Critical Issues: 2
Total Issues on final build 15
No of times PR was sent for Functionality correction: 4
PR breaks existing functionality: Yes

**Pull request merged**
