### PR TITLE
Alert Message

### PR DESCRIPTION
**Pull request by Gurmeenkour99**
Created different sessions for payment and others

### CODE REVIEW

**Comment by bhanu2217** [comment]
Do we have any issue for this? can we link the issue with it?

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by sandesh556 — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
1. Issue:- when we are paying full amount from credit balance that time success message showing old one.
image
2.  When purchase freelancer that time also success message showing old one.
image

**Comment by SarfrazS** [comment]
- [ ] Perpetual plan doing renew with credits getting below error.
image

**Review by SarfrazS — APPROVED** [review]
ALL Pointed issues are fixed.
**First round testing summary:-**
**Time taking in hours/days:- 8 hours**
**Total issues: 5**
Minor : 5
Major: 0
Critical: 0

Freelancer
image
Renew with stripe
image
Renew with Credit
image
Purchase with Razorpay
image

**Pull request merged**
