### PR TITLE
Laravel 9 upgrade with php8, Innodb, Admin, and Client panel theme update

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Laravel 9 upgrade with php8, Innodb, Admin, and Client panel theme update

#1690 

**Bugs tracked here:**
https://docs.google.com/document/d/1TBgwF_ELrlxkZUUWV9QyuELTDuIfg2LXX-JEcLQfukw/edit

**Issues found in Round 2 of Testing:**
https://docs.google.com/spreadsheets/d/1CB139UvzvUtB1JOHYP0nmEqjxdoHQPGWLGjD_niH9pw

### CODE REVIEW

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please let me know in which server I can test this pr.

**Comment by SarfrazS** [comment]
where you tested please share server details i will check on the same server also.

**Comment by sowmiyasubramaniyan** [comment]
> @sowmiyasubramaniyan Please let me know in which server I can test this pr.

I will share with you

**Comment by Sheetal34** [comment]
Getting this, while installation 
image
Unable to proceed testing

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
Tested pr with given credentials
https://qa.faveodemo.com/sheetal/public/
demoadmin
Demopass@123

Whichever issues found till now, updated in document
https://docs.google.com/document/d/1KqfgwJml_Kq70re9KZLNHAUbzAYER-Ub32jL18ZoEec/edit

Note:- Still testing, not completed yet.

**Comment by sandesh556** [comment]
@Sheetal34 do verify if they are happening in master also

**Comment by Sheetal34** [comment]
Separate issues raised for existing issues:
https://github.com/ladybirdweb/agora-invoicing-community/issues/1916
https://github.com/ladybirdweb/agora-invoicing-community/issues/1915
https://github.com/ladybirdweb/agora-invoicing-community/issues/1914

**Review by SarfrazS — COMMENTED** [review]
@sowmiyasubramaniyan Please import live db on my instance and run migration again and let me i will cross check all below issues again. testing is not completed yet.
https://docs.google.com/document/d/1TBgwF_ELrlxkZUUWV9QyuELTDuIfg2LXX-JEcLQfukw/edit

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Testing with fresh installation on server:**
Still mentioned issues are not fixed. Whichever issues are not fixed are updated in documentation
Found new issues also. Updated in documentation
https://docs.google.com/document/d/1KqfgwJml_Kq70re9KZLNHAUbzAYER-Ub32jL18ZoEec/edit?skip_itp2_check=true

Note: Testing not completed yet.

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with given credentials:**
https://qa.faveodemo.com/saifagora/public/
sarfraz.ansari@ladybirdweb.com
786Saifu@

Found issues updated in documentation.
https://docs.google.com/document/d/1KqfgwJml_Kq70re9KZLNHAUbzAYER-Ub32jL18ZoEec/edit?skip_itp2_check=true

Note: Checked maximum possible scenarios. Once mentioned issues are fixed. Will check for other scenarios.

**Comment by sowmiyasubramaniyan** [comment]
https://docs.google.com/spreadsheets/d/1CB139UvzvUtB1JOHYP0nmEqjxdoHQPGWLGjD_niH9pw
  I have updated the bug status on the above sheet.

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
Tested in server intsance 
https://qa.faveodemo.com/saifagora/public/
sarfraz.ansari@ladybirdweb.com
786Saifu@
Still mentioned issues are not fixed yet. Found new issues also updated on sheet
https://docs.google.com/spreadsheets/d/1CB139UvzvUtB1JOHYP0nmEqjxdoHQPGWLGjD_niH9pw/edit#gid=0

**Review by manikz5 — CHANGES_REQUESTED** [review]
Testing PR, two issues occurred in Pages and plans module also updated in bug sheet, testing not completed yet.
https://docs.google.com/spreadsheets/d/1CB139UvzvUtB1JOHYP0nmEqjxdoHQPGWLGjD_niH9pw/edit?usp=sharing

**Review by manikz5 — CHANGES_REQUESTED** [review]
Tried installation of faveo with license key generated unable to see installation details on View Order page, below is the screenshot attached for reference : 
installationpathmissing

**Comment by sandesh556** [comment]
@manikz5 you need to change certain billing URL inside faveo to your billing URLs then only this will work otherwise it is trying to contact live billing itself.

**Comment by bhanu2217** [comment]
> @manikz5 you need to change certain billing URL inside faveo code base to your billing URLs then only this will work otherwise it is trying to contact live billing itself.

Please share the location with him, where he can make these changes to test this feature

**Comment by SarfrazS** [comment]
we changed the billing and license URL in below places:-

- apl_core_configuration.php
- apl_core_functions.php
- update_core_configuration.php

Only on billing it is not showing
image


Note:- On the license manager it is showing.
image

image

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
Issue 1:Dependencies have vanished in all the products when we edit any product and navigating to Error Argument page.


nov25depend

**Comment by Sheetal34** [comment]
@sowmiyasubramaniyan All pointed issues are fixed or still you are working on it. If you are still working on it, please give us an update by when you can fix all issues, so that we can proceed with testing.

**Comment by sandesh556** [comment]
image
Why is mail chimp removed from your branch? was that integration tested?

**Review by SarfrazS — CHANGES_REQUESTED** [review]
pointed issues are fixed but other issues occurred updated to developer
Issues:- If products are there on cart then renew is not working.
image

**Comment by sowmiyasubramaniyan** [comment]
> pointed issues are fixed but other issues occurred updated to developer Issues:- If products are there on cart then renew is not working. image

This is an existing issue

**Review by SarfrazS — APPROVED** [review]
I retested all pointed issues all are fixed. Now working fine.
Note:- still all database tables are not converted on INNODB  some of are still showing MYISAM
image

**Review by SarfrazS — APPROVED** [review]
After ran this command php artisan database:sync

**Review by sandesh556 — APPROVED** [review]

**Pull request merged**
