### PR TITLE
Issue 872

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Issue fix:#872
      This PR is about created social media to a more User friendly.

### CODE REVIEW

**Review by sandesh556 — APPROVED** [review]

**Review by RafficMohammed — APPROVED** [review]

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
- [ ] Issue 1:In the social media page, without giving the domain name for the social link. still able to proceed further.

- [ ] Issue 2:In the home page after adding social media link. still, the icon for social login is not showing in the follow us page and alignment is not proper.


Note: Pointed the issues while presenting the demo.

**Review by priyadarshini2101 — CHANGES_REQUESTED** [review]
Tested the pr in existing db found issues.

Checked for the pointed issue. In existing there are 4 fields in social media page. now Reduced to two fields.

- [ ] Issue 1:After creating the social media link, the icon of social media are not picking default color like facebook, twitter and linked In.

jul13socialicons

Note: Found another issue created seperate issue for the same and explained to sowmya.

**Review by priyadarshini2101 — APPROVED** [review]
Tested the pr with existing db on server.


jul20icons

Discussed with @sowmiyasubramaniyan. Only Few social media website links are hardcoded for this pr. So, only for those social media websites and applications the icons and color will pick by default.

**Comment by sowmiyasubramaniyan** [comment]
Below are the Hard coded social media icons :
    Facebook,Linkedin,RSS,Google,Pinterest,Youtube,Github,Instagram,Skype,Vk,Xing,Tumblr,Reddit,Envelope
For these only social media icons and colors will pick

**Review by Sheetal34 — APPROVED** [review]
Tested for mentioned fixes. Working fine.
image
image

**Pull request merged**
