### PR TITLE
Razorpay Subscription

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
The following command need to run:
          php artisan migrate

### CODE REVIEW

**Review by sandesh556 — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
image

Just now i purchases HD Enterprise with Razorpay i got a success invoice message.
image
**Now When I view the order Auto-renewal option is not showing. Please can you check** 
image

**Comment by sowmiyasubramaniyan** [comment]
> image
> 
> Just now i purchases HD Enterprise with Razorpay i got a success invoice message. image **Now When I view the order Auto-renewal option is not showing. Please can you check** image

@SarfrazS Fixed this

**Review by SarfrazS — CHANGES_REQUESTED** [review]
After executing renewal command we are not getting auto payment mail. that's why with  USD Auto-renewal not working.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
With USD price while updating card details from order view page showing wrong price and showing below alert message.
image
image
image
USD price is showing different for different countries cross checking after that will update.

**Review by SarfrazS — APPROVED** [review]
Pointed issues are fixed, Now working fine.

**Comment by sowmiyasubramaniyan** [comment]
Unable to merge this branch so I have created the new P.R.
 https://github.com/ladybirdweb/agora-invoicing-community/pull/2307

**Pull request closed without merging**
