### PR TITLE
Release - 4.0.2.1

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Fixes: 
#2987 
#2975 
#2974
#2971 
#2969 
#2444
#1719 
#1720

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] Issue1 when we click on All users side bar UI breaking.

**Comment by sowmiyasubramaniyan** [comment]
> * [ ]  Issue1 when we click on All users side bar UI breaking.
>   image

Fixed

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] with live srtipe key while purchasing product getting below error.
image

**Review by SarfrazS — APPROVED** [review]
I verified all linked issues and then basic functionalities are working fine.
I cross-verified with live card also working fine.

**Pull request merged**
