### PR TITLE
Hotfix release 

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Run the following command:
php artisan db:seed --class="Database\Seeders\v4_0_1\DatabaseSeeder"

### CODE REVIEW

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] UI need to change for this validation,  still same please check and fix it.

image

**Comment by SarfrazS** [comment]
All Pointed issues are fixed. Two more new issues developer is working on it.

**Comment by SarfrazS** [comment]
- [ ] Remember me 2fa not working.
- [ ] When we click on store group getting an invalid currency error.
- [ ] KB link not working. getting below error
Screenshot 2024-01-12 114622

**Review by SarfrazS — APPROVED** [review]
The pointed issues are fixed and now working fine in three browsers. Chrome Firefox and Edge with the latest version.

**Review by sandesh556 — APPROVED** [review]

**Pull request merged**
