### PR TITLE
Added Demo Page And Few Button Changes

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Old pr : https://github.com/ladybirdweb/agora-invoicing-community/pull/2299

### CODE REVIEW

**Review by SarfrazS — APPROVED** [review]
Demo Request functionality working fine.
Below configuration, we have to do then it will create a ticket on the helpdesk.
Step1- First Configure agora system mail. (faveo2223@gmail.com)
Step2- Save Company email id in Agora(helpdeskfaveo@outlook.com)
Step3- Configure helpdesk system mail.(helpdeskfaveo@outlook.com)
Step4- Login agora and there you can Demo Request button.
Step5- Click and enter details.
Step6-  Company mail will receive Demo request mail.
Step7- Once the helpdesk cron will execute the ticket will create in the helpdesk with the demo request email id.
Step8- After that, once the Helpdesk staff replies to his ticket request user will receive mail from the Helpdesk mail. 
image

image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Please fix this issue on high priority we are unable to continue testing because of this issue.
image

**Comment by sowmiyasubramaniyan** [comment]
> Please fix this issue on high priority we are unable to continue testing because of this issue. image

Already fixed.

**Review by Sabaric12 — DISMISSED** [review]
Tested this pr with the existing installation
The mentioned issue is working fine as I have discussed with the developer about the recaptcha he said he removed the recaptcha changes except this all the tickets are generated from the faveo instance
Step1- First Configure agora system mail. (vickychetty27@gmail.com)
Step2- Save Company email id in Agora(sabaric332@gmail.com)
Step3- Configure helpdesk system mail.(sabaric332@gmail.com)
Step4- Login agora and there you can Demo Request button.
Step5- Click and enter details.
Step6- Company mail will receive Demo request mail.
Step7- Once the helpdesk cron will execute the ticket will create in the helpdesk with the demo request email id.
Step8- After that, once the Helpdesk staff replies to his ticket request user will receive mail from the Helpdesk mail.
Screenshot from 2023-08-17 17-34-14

**Pull request merged**
