### PR TITLE
Remove option for coupon code on checkout page

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Fix : #2016

### CODE REVIEW

**Review by sandesh556 — APPROVED** [review]

**Review by ajaz-ul-haq — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Query:- Coupon code applied again we click on apply button why show an invalid coupon instead of already applied has applied?
image

**Comment by sowmiyasubramaniyan** [comment]
> Why do we want to remove coupon code on the checkout page?

 if the user wants to try with a different coupon or if they're going to remove this will be useful.

**Comment by bhanu2217** [comment]
> Query:- Coupon code applied again we click on apply button why show an invalid coupon instead of an already coupon applied? image

- I would show remove button only if earlier coupon is applied on the cart/checkout page. If there is no coupon applied, no need to show remove button 
- There is already Cross button next to coupon text, do we still need one more red button?

**Comment by sowmiyasubramaniyan** [comment]
> > Query:- Coupon code applied again we click on apply button why show an invalid coupon instead of an already coupon applied? image
> 
> * I would show remove button only if earlier coupon is applied on the cart/checkout page. If there is no coupon applied, no need to show remove button
> * There is already Cross button next to coupon text, do we still need one more red button?

Screenshot from 2023-07-31 17-50-15
I have added the cross icon to remove the coupon near the discount itself.

**Comment by bhanu2217** [comment]
**Feedback:**

- Show cross button next to discount amount. This will remove discount from checkout
- Apply button can be used to apply coupon code again even if there is existing coupon code, it will clear the existing one
- Show discount amount instead of(%)in
- After the discount amount or before or somewhere show the coupon code which was applied
- Capture the coupon code applied, so admin others will know discount was given based on what?

**Review by Sabaric12 — DISMISSED** [review]
Tested this pr with the existing installation
The Mentioned issues and feedback issues are working fine
https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/ecad1837-0920-41c4-9d01-d1ee126c2f75

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] Issue1:- I created two coupons Ind2023 and USD250 for HD Enterprise. Now user applied USD250 successfully. Again user trying to apply Ind2023 Coupon that time we are showing alert message which is not user friendly. Please change the alert message.
image

- [ ] Issue2:- I added two products on cart and applied valid coupon for one product till here working fine. once we removed applied coupon then price is showing wrong for discount product
HD Enterprise price showing wrong.
image

image

- [ ] Issue3:- With percentage coupon, Coupon is applied on products price is reduced but coupon discount amount showing zero.
image
After applied coupon
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Still percentage coupon discount not calculating properly. Shown to developer.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
Still existing issue are not fixed. Please fix and let me know.
Issue1:- I added two products on cart Firstly i applied for one product coupon shows discount amount, again i applied coupon for second product here also shows coupon discount amount and pervious one also. 
Issue2:-  Same thing for SaaS.
Issue3:- When removed applied coupon from cart then not showing actual price.
Addmedia

**Comment by Sabaric12** [comment]
Tested this pr with the existing installation
Now the coupon code not able to apply

https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/abb756a4-7012-46f6-a7bc-1a94f65e6c98

**Review by Sabaric12 — DISMISSED** [review]
Tested this pr with the existing installation
The mentioned issues are working fine

**Review by SarfrazS — CHANGES_REQUESTED** [review]
@sowmiyasubramaniyan i'm requesting to you please fix pointed issues but not break dependency. Now i m not able to pay with both payment gateway. Getting below error.
image
image

**Comment by SarfrazS** [comment]
@Sabaric12 Have you tested payment functionality?

**Comment by sowmiyasubramaniyan** [comment]
> @sowmiyasubramaniyan i'm requesting to you please fix pointed issues but not break dependency. Now i m not able to pay with both payment gateway. Getting below error. image image

Both payment gateways with and without coupon code are working fine. Please check again and clear the browser cache.and please share your test instance credential I will check there also

**Comment by SarfrazS** [comment]
@sowmiyasubramaniyan Please resolved conflicts and let me know.

**Review by SarfrazS — COMMENTED** [review]
Remove option for coupon code on checkout page functionality working. Once code conflicts resolved after that will check basic then will approve it.
image

**Review by SarfrazS — APPROVED** [review]
Working fine

**Pull request merged**
