### PR TITLE
Pre releases

### PR DESCRIPTION
**Pull request by RafficMohammed**
Run the following command:
php artisan migrate
php artisan db:seed --class="Database\Seeders\v4_0_2\DatabaseSeeder"

### CODE REVIEW

**Review by sowmiyasubramaniyan — APPROVED** [review]

**Comment by sandesh556** [comment]
@sowmiyasubramaniyan create a seperate issue or you can add it in this PR also, This pre release should also be present in the ui like a radio button where you can choose yes or no. Just like how we have for restricted release

**Review by sandesh556 — APPROVED** [review]

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] Missing feature:- Please add pre-release label on download popup data table. So that user can easily identify which version is beta and which version is production.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
- [ ] Issue:- Unable to add files with pre_release version.

**Review by SarfrazS — APPROVED** [review]
Pre-Release checkbox we added on add file page before we have private and restricted checkbox.
While adding product version and if we checked pre release checkbox than in download popup data table pre-release label showing.
image

**Pull request merged**
