### PR TITLE
Admin panel Orders Display

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**

### CODE REVIEW

**Review by laksh-22 — APPROVED** [review]

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with existing db on server:**
Facing issue there:

- [ ] I executed order at 10:58 PM  but date showing 19 May 2023
image

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Checked with existing db on server:**
Mentioned issue not fixed yet

- [ ] While executing order, In client panel, date showing correct 
image
But in admin panel it's showing incorrect 
image

Same issue facing while creating invoice 
image

**Review by Sheetal34 — DISMISSED** [review]
Mentioned issues are fixed.
For mentioned issue, created separate issue for that as discussed
https://github.com/ladybirdweb/agora-invoicing-community/issues/2245

**Review by SarfrazS — DISMISSED** [review]
working fine as expected.

**Pull request merged**
