### PR TITLE
Forgot password security

### PR DESCRIPTION
**Pull request by ashu555**
Fixes https://github.com/ladybirdweb/agora-invoicing-community/issues/1142
Fixes https://github.com/ladybirdweb/agora-invoicing-community/issues/1141

For issue #1142 create recaptcha keys for your domains here
https://www.google.com/recaptcha/admin
Use v2 recaptcha when you register here

### CODE REVIEW

**Comment by mverma16** [comment]
rebase this branch with base development branch

**Comment by bhanu2217** [comment]
@ashu555 What is the status on this?

**Comment by ashu555** [comment]
> Issue is there with below scenario:-
> 
> 1. Recaptcha is enabled.
> 2. 2FA is also enabled for that user who is trying to forget the password.
> 3. User Received reset password link on the mail.
> 4. email and billing URL not opened in the same browser in the different browsers they open.
>    Now click on Reset password link then it's not redirecting to OPT page it's redirecting to reset password page.
> 
> Issue:- Please define a certain time period to session out reset password link.
> Issue:- If we reset password successfully and again user try to reset the password with the same link. they are able to reset second time also with same link so it's wrong.

Fixed

**Comment by ashu555** [comment]
> > Issue is there with below scenario:-
> > 
> > 1. Recaptcha is enabled.
> > 2. 2FA is also enabled for that user who is trying to forget the password.
> > 3. User Received reset password link on the mail.
> > 4. email and billing URL not opened in the same browser in the different browsers they open.
> >    Now click on Reset password link then it's not redirecting to OPT page it's redirecting to reset password page.
> > 
> > Issue:- Please define a certain time period to session out reset password link.
> > Issue:- If we reset password successfully and again user try to reset the password with the same link. they are able to reset second time also with same link so it's wrong.
> 
> Fixed

The last two issues are known issues and fixed in different branch.You can test rest of the issues

**Comment by bhanu2217** [comment]
**For security reason:**

- Forgot password link should be time bound, See other system, what should be the ideal time the link is valid for
- Once the link is used it cannot be resued to reset the password

Thank You.

**Comment by bindu95** [comment]
**Scenario** 
Install in the master branch
Configure email
Make settings for Recaptcha
Now checkout to Ashutosh branch
Check for Recaptcha (Showing invalid site key)
Note: Did hard refresh, cleared cookies from browser yet not coming

Now in admin panel disable Recaptcha setting and enable then it's working

**Comment by ashu555** [comment]
> **Scenario**
> Install in the master branch
> Configure email
> Make settings for Recaptcha
> Now checkout to Ashutosh branch
> Check for Recaptcha (Showing invalid site key)
> Note: Did hard refresh, cleared cookies from browser yet not coming
> 
> Now in admin panel disable Recaptcha setting and enable then it's working
> @ashu555 please let me know why its happening

I changed few things on how captcha is getting saved. Earlier there was a bug while it was getting saved in master branch.

**Comment by SarfrazS** [comment]
when we enter a wrong or unregister email id alert message is showing but not user friendly. i am approved but we have correct it.
image

**Pull request merged**
