### PR TITLE
Client Panel,Invoice and Orders sorting issue fix

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**

### CODE REVIEW

**Review by laksh-22 — APPROVED** [review]

**Review by ajaz-ul-haq — APPROVED** [review]

**Review by Sheetal34 — CHANGES_REQUESTED** [review]
**Tested with existing db on server**
Facing issue there
- [ ] Client Panel > My orders > Sorting not working for recently executed orders

**Comment by sowmiyasubramaniyan** [comment]
> **Tested with existing db on server** Facing issue there
> 
> * [x]  Client Panel > My orders > Sorting not working for recently executed orders

Fixed

**Review by Sheetal34 — DISMISSED** [review]
**Tested with existing db on server:**
Mentioned issue is fixed now.

- [ ] Now recently executed orders and invoices are showing at top while sorting
image
image

**Review by SarfrazS — CHANGES_REQUESTED** [review]
in order data table sorting with order not working.
Dashboard

**Review by SarfrazS — CHANGES_REQUESTED** [review]
This is last commits
image
Still in order data table sort by order from order column not working.

**Review by SarfrazS — APPROVED** [review]
Pointed issue fixed. 
image
image

**Pull request merged**
