### PR TITLE
add missing states in the seeder

### PR DESCRIPTION
**Pull request by sowmiyasubramaniyan**
Issue fix: #1695

### CODE REVIEW

**Review by sandesh556 — DISMISSED** [review]

**Review by ajaz-ul-haq — DISMISSED** [review]

**Comment by ajaz-ul-haq** [comment]
please check the commits once

**Review by ajaz-ul-haq — DISMISSED** [review]

**Review by sandesh556 — DISMISSED** [review]

**Comment by sowmiyasubramaniyan** [comment]
@Sheetal34  Kosovo doesn't have states, Kosovo is divided into 38 municipalities.

**Comment by bhanu2217** [comment]
> @Sheetal34 Kosovo doesn't have states, Kosovo is divided into 38 municipalities.

State is a mandatory field. Will user be able to register without choosing state field?

**Comment by sowmiyasubramaniyan** [comment]
**Kosovo was part of Serbia until it declared independence in 2008. However, all countries do not recognise its status as an independent state. The issue of Kosovo's status is complex. While Serbia still considers Kosovo part of its territory, Kosovo operates as a de facto independent state, with its own government, constitution, and institutions.**

We have the option to select Kosovo regions from Serbia country, I  will remove Kosovo from the country field.

**Review by Sheetal34 — APPROVED** [review]
Checked for mentioned issues. Working fine.
Now state field will not be the required field.

**Review by SarfrazS — CHANGES_REQUESTED** [review]
For seeder i ran this command php artisan database:sync  all ready 5+ minutes over but still not executed.
image

**Review by SarfrazS — APPROVED** [review]
I checked on local with fresh installation and on server with existing db working fine.

**Pull request merged**
